import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'

import Categoria from '#models/categoria'
import Registro from '#models/registro'

export default class extends BaseSeeder {
  public async run() {
    const alimentos = await Categoria.findByOrFail('slug', 'alimentos')
    const bebidas = await Categoria.findByOrFail('slug', 'bebidas')
    const roupas = await Categoria.findByOrFail('slug', 'roupas')
    const pecas = await Categoria.findByOrFail('slug', 'pecas-automotivas')
    const funcionarios = await Categoria.findByOrFail('slug', 'funcionarios')
    const eletronicos = await Categoria.findByOrFail('slug', 'eletronicos')

    await Registro.createMany([
      /* ALIMENTOS */
      {
        categoriaId: alimentos.id,
        sku: 'ALM001',
        nome: 'Arroz',
        preco: 25.0,
        quantidade: 50,
        ativo: true,
        marca: 'Tio João',
        validade: DateTime.fromISO('2026-01-01'),
        dadosJson: { tipo: 'Integral', embalagem: '1kg' },
      },
      {
        categoriaId: alimentos.id,
        sku: 'ALM002',
        nome: 'Feijão',
        preco: 18.0,
        quantidade: 30,
        ativo: true,
        marca: 'Carioca',
        validade: DateTime.fromISO('2026-01-01'),
        dadosJson: { tipo: 'Carioca', embalagem: '1kg' },
      },

      /* BEBIDAS */
      {
        categoriaId: bebidas.id,
        sku: 'BEB001',
        nome: 'Refrigerante Cola',
        preco: 6.5,
        quantidade: 100,
        ativo: true,
        marca: 'Coca-Cola',
        validade: DateTime.fromISO('2026-01-01'),
        dadosJson: { volume: '2L', tipo: 'Gaseificado' },
      },

      /* ROUPAS */
      {
        categoriaId: roupas.id,
        sku: 'ROU001',
        nome: 'Camiseta Polo',
        preco: 79.9,
        quantidade: 25,
        ativo: true,
        marca: 'Lacoste',
        dadosJson: { tamanho: 'M', cor: 'Azul' },
      },

      /* PEÇAS */
      {
        categoriaId: pecas.id,
        sku: 'PEC001',
        nome: 'Filtro de Óleo',
        preco: 45.0,
        quantidade: 60,
        ativo: true,
        marca: 'Bosch',
        modelo: 'Fiat Uno 2010',
        peso: 0.5,
        dadosJson: { tipo: 'Filtro', aplicacao: 'Motor 1.0' },
      },

      /* FUNCIONÁRIOS */
      {
        categoriaId: funcionarios.id,
        sku: 'FUNC001',
        nome: 'João Silva',
        ativo: true,
        dadosJson: {
          cargo: 'Instalador',
          salario: 2500.0,
          dataAdmissao: '2023-03-15',
        },
      },

      /* ELETRÔNICOS */
      {
        categoriaId: eletronicos.id,
        sku: 'ELE001',
        nome: 'Notebook Gamer',
        preco: 7500.0,
        quantidade: 10,
        ativo: true,
        marca: 'Dell',
        modelo: 'G15',
        dadosJson: {
          processador: 'Intel i7',
          ram: '16GB',
          armazenamento: '512GB SSD',
        },
      },
      /* ALIMENTOS */
      {
        categoriaId: alimentos.id,
        sku: 'ALM003',
        nome: 'Macarrão Espaguete',
        preco: 6.5,
        quantidade: 80,
        ativo: true,
        marca: 'Barilla',
        validade: DateTime.fromISO('2026-03-01'),
        dadosJson: { tipo: 'Espaguete', peso: '500g' },
      },
      {
        categoriaId: alimentos.id,
        sku: 'ALM004',
        nome: 'Açúcar Refinado',
        preco: 4.2,
        quantidade: 120,
        ativo: true,
        marca: 'União',
        validade: DateTime.fromISO('2027-01-01'),
        dadosJson: { tipo: 'Refinado', peso: '1kg' },
      },
      {
        categoriaId: alimentos.id,
        sku: 'ALM005',
        nome: 'Café Torrado',
        preco: 14.9,
        quantidade: 70,
        ativo: true,
        marca: 'Pilão',
        validade: DateTime.fromISO('2026-08-01'),
        dadosJson: { tipo: 'Tradicional', peso: '500g' },
      },

      /* BEBIDAS */
      {
        categoriaId: bebidas.id,
        sku: 'BEB002',
        nome: 'Suco de Laranja',
        preco: 7.5,
        quantidade: 60,
        ativo: true,
        marca: 'Del Valle',
        validade: DateTime.fromISO('2026-02-01'),
        dadosJson: { volume: '1L', tipo: 'Natural' },
      },
      {
        categoriaId: bebidas.id,
        sku: 'BEB003',
        nome: 'Água Mineral',
        preco: 2.5,
        quantidade: 200,
        ativo: true,
        marca: 'Crystal',
        validade: DateTime.fromISO('2027-01-01'),
        dadosJson: { volume: '500ml', tipo: 'Sem gás' },
      },
      {
        categoriaId: bebidas.id,
        sku: 'BEB004',
        nome: 'Cerveja Lager',
        preco: 3.9,
        quantidade: 150,
        ativo: true,
        marca: 'Skol',
        validade: DateTime.fromISO('2026-05-01'),
        dadosJson: { volume: '350ml', tipo: 'Alcoólica' },
      },

      /* ROUPAS */
      {
        categoriaId: roupas.id,
        sku: 'ROU002',
        nome: 'Calça Jeans',
        preco: 129.9,
        quantidade: 40,
        ativo: true,
        marca: 'Levis',
        dadosJson: { tamanho: '42', cor: 'Azul' },
      },
      {
        categoriaId: roupas.id,
        sku: 'ROU003',
        nome: 'Jaqueta',
        preco: 199.9,
        quantidade: 20,
        ativo: true,
        marca: 'Nike',
        dadosJson: { tamanho: 'G', cor: 'Preto' },
      },
      {
        categoriaId: roupas.id,
        sku: 'ROU004',
        nome: 'Tênis Esportivo',
        preco: 299.9,
        quantidade: 35,
        ativo: true,
        marca: 'Adidas',
        dadosJson: { tamanho: '41', cor: 'Branco' },
      },

      /* PEÇAS AUTOMOTIVAS */
      {
        categoriaId: pecas.id,
        sku: 'PEC002',
        nome: 'Pastilha de Freio',
        preco: 89.9,
        quantidade: 50,
        ativo: true,
        marca: 'Brembo',
        modelo: 'Honda Civic',
        peso: 1.2,
        dadosJson: { tipo: 'Freio', posicao: 'Dianteira' },
      },
      {
        categoriaId: pecas.id,
        sku: 'PEC003',
        nome: 'Bateria Automotiva',
        preco: 450.0,
        quantidade: 15,
        ativo: true,
        marca: 'Moura',
        modelo: '60Ah',
        peso: 12,
        dadosJson: { voltagem: '12V', capacidade: '60Ah' },
      },

      /* FUNCIONÁRIOS */
      {
        categoriaId: funcionarios.id,
        sku: 'FUNC002',
        nome: 'Maria Souza',
        ativo: true,
        dadosJson: {
          cargo: 'RH',
          salario: 3200.0,
          dataAdmissao: '2022-06-10',
        },
      },
      {
        categoriaId: funcionarios.id,
        sku: 'FUNC003',
        nome: 'Carlos Pereira',
        ativo: true,
        dadosJson: {
          cargo: 'Gerente',
          salario: 5000.0,
          dataAdmissao: '2021-01-20',
        },
      },

      /* ELETRÔNICOS */
      {
        categoriaId: eletronicos.id,
        sku: 'ELE002',
        nome: 'Smartphone',
        preco: 2500.0,
        quantidade: 25,
        ativo: true,
        marca: 'Samsung',
        modelo: 'Galaxy S23',
        dadosJson: {
          armazenamento: '256GB',
          ram: '8GB',
        },
      },
      {
        categoriaId: eletronicos.id,
        sku: 'ELE003',
        nome: 'TV LED',
        preco: 3200.0,
        quantidade: 12,
        ativo: true,
        marca: 'LG',
        modelo: '55"',
        dadosJson: {
          resolucao: '4K',
          tamanho: '55 polegadas',
        },
      },
      {
        categoriaId: eletronicos.id,
        sku: 'ELE004',
        nome: 'Fone Bluetooth',
        preco: 199.9,
        quantidade: 80,
        ativo: true,
        marca: 'JBL',
        dadosJson: {
          tipo: 'Sem fio',
          bateria: '20h',
        },
      },
      {
        categoriaId: funcionarios.id,
        sku: 'FUNC010',
        nome: 'Ana Costa',
        ativo: true,
        dadosJson: {
          cargo: 'Gerente',
          salario: 6500,
          dataAdmissao: '2020-05-10',
        },
      },
      {
        categoriaId: funcionarios.id,
        sku: 'FUNC011',
        nome: 'Lucas Mendes',
        ativo: true,
        dadosJson: {
          cargo: 'Instalador',
          salario: 2800,
          dataAdmissao: '2022-08-15',
        },
      },

      {
        categoriaId: eletronicos.id,
        sku: 'ELE010',
        nome: 'Smartphone Samsung Galaxy S23',
        preco: 3499.9,
        quantidade: 18,
        ativo: true,
        marca: 'Samsung',
        modelo: 'S23',
        dadosJson: {
          ram: '8GB',
          armazenamento: '256GB',
        },
      },
      {
        categoriaId: eletronicos.id,
        sku: 'ELE011',
        nome: 'Notebook Dell Inspiron 15',
        preco: 4200.0,
        quantidade: 12,
        ativo: true,
        marca: 'Dell',
        modelo: 'Inspiron 15',
        dadosJson: {
          ram: '16GB',
          armazenamento: '512GB SSD',
        },
      },
      {
        categoriaId: eletronicos.id,
        sku: 'ELE012',
        nome: 'Smart TV LG 55" 4K',
        preco: 3200.0,
        quantidade: 8,
        ativo: true,
        marca: 'LG',
        modelo: '55UQ',
        dadosJson: {
          resolucao: '4K',
          tamanho: '55"',
        },
      },

      {
        categoriaId: pecas.id,
        sku: 'PEC010',
        nome: 'Filtro de Ar Motor',
        preco: 39.9,
        quantidade: 45,
        ativo: true,
        marca: 'Bosch',
        modelo: 'Volkswagen Gol',
        peso: 0.4,
        dadosJson: { tipo: 'Filtro', aplicacao: 'Motor 1.6' },
      },
      {
        categoriaId: pecas.id,
        sku: 'PEC011',
        nome: 'Bateria 60Ah',
        preco: 420.0,
        quantidade: 10,
        ativo: true,
        marca: 'Moura',
        modelo: 'Universal',
        peso: 12,
        dadosJson: { voltagem: '12V', capacidade: '60Ah' },
      },
      {
        categoriaId: pecas.id,
        sku: 'PEC012',
        nome: 'Pastilha de Freio Dianteira',
        preco: 95.0,
        quantidade: 30,
        ativo: true,
        marca: 'Brembo',
        modelo: 'Honda Civic',
        peso: 1.1,
        dadosJson: { tipo: 'Freio', posicao: 'Dianteira' },
      },

      {
        categoriaId: roupas.id,
        sku: 'ROU010',
        nome: 'Camiseta Básica Preta',
        preco: 49.9,
        quantidade: 35,
        ativo: true,
        marca: 'Hering',
        dadosJson: { tamanho: 'M', cor: 'Preto' },
      },
      {
        categoriaId: roupas.id,
        sku: 'ROU011',
        nome: 'Calça Jeans Slim Azul',
        preco: 139.9,
        quantidade: 25,
        ativo: true,
        marca: 'Levis',
        dadosJson: { tamanho: '42', cor: 'Azul' },
      },
      {
        categoriaId: roupas.id,
        sku: 'ROU012',
        nome: 'Jaqueta Corta Vento',
        preco: 179.9,
        quantidade: 15,
        ativo: true,
        marca: 'Nike',
        dadosJson: { tamanho: 'G', cor: 'Preto' },
      },
      {
        categoriaId: roupas.id,
        sku: 'ROU013',
        nome: 'Tênis Running Branco',
        preco: 299.9,
        quantidade: 20,
        ativo: true,
        marca: 'Adidas',
        dadosJson: { tamanho: '41', cor: 'Branco' },
      },

      {
        categoriaId: bebidas.id,
        sku: 'BEB010',
        nome: 'Refrigerante Coca-Cola 2L',
        preco: 9.9,
        quantidade: 150,
        ativo: true,
        marca: 'Coca-Cola',
        validade: DateTime.fromISO('2026-06-01'),
        dadosJson: { volume: '2L', tipo: 'Gaseificado' },
      },
      {
        categoriaId: bebidas.id,
        sku: 'BEB011',
        nome: 'Guaraná Antarctica 2L',
        preco: 8.5,
        quantidade: 140,
        ativo: true,
        marca: 'Antarctica',
        validade: DateTime.fromISO('2026-06-10'),
        dadosJson: { volume: '2L', tipo: 'Gaseificado' },
      },
      {
        categoriaId: bebidas.id,
        sku: 'BEB012',
        nome: 'Suco de Uva Integral 1L',
        preco: 14.9,
        quantidade: 70,
        ativo: true,
        marca: 'Aurora',
        validade: DateTime.fromISO('2026-04-01'),
        dadosJson: { volume: '1L', tipo: 'Integral' },
      },
      {
        categoriaId: bebidas.id,
        sku: 'BEB013',
        nome: 'Água Mineral Crystal 500ml',
        preco: 2.2,
        quantidade: 300,
        ativo: true,
        marca: 'Crystal',
        validade: DateTime.fromISO('2027-01-01'),
        dadosJson: { volume: '500ml', tipo: 'Sem gás' },
      },

      {
        categoriaId: alimentos.id,
        sku: 'ALM010',
        nome: 'Arroz Branco 5kg',
        preco: 32.9,
        quantidade: 40,
        ativo: true,
        marca: 'Camil',
        validade: DateTime.fromISO('2026-06-01'),
        dadosJson: { tipo: 'Branco', embalagem: '5kg' },
      },
      {
        categoriaId: alimentos.id,
        sku: 'ALM011',
        nome: 'Feijão Preto 1kg',
        preco: 9.5,
        quantidade: 60,
        ativo: true,
        marca: 'Kicaldo',
        validade: DateTime.fromISO('2026-05-10'),
        dadosJson: { tipo: 'Preto', embalagem: '1kg' },
      },
      {
        categoriaId: alimentos.id,
        sku: 'ALM012',
        nome: 'Macarrão Parafuso 500g',
        preco: 5.9,
        quantidade: 80,
        ativo: true,
        marca: 'Renata',
        validade: DateTime.fromISO('2026-07-01'),
        dadosJson: { tipo: 'Parafuso', embalagem: '500g' },
      },
      {
        categoriaId: alimentos.id,
        sku: 'ALM013',
        nome: 'Óleo de Soja 900ml',
        preco: 7.8,
        quantidade: 90,
        ativo: true,
        marca: 'Soya',
        validade: DateTime.fromISO('2026-09-01'),
        dadosJson: { tipo: 'Soja', volume: '900ml' },
      },
      {
        categoriaId: alimentos.id,
        sku: 'ALM014',
        nome: 'Leite Integral 1L',
        preco: 4.9,
        quantidade: 120,
        ativo: true,
        marca: 'Piracanjuba',
        validade: DateTime.fromISO('2026-02-15'),
        dadosJson: { tipo: 'Integral', volume: '1L' },
      },
    ])
  }
}
