/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Campos: () => import('#controllers/campos_controller'),
  Categorias: () => import('#controllers/categorias_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Registros: () => import('#controllers/registros_controller'),
}
