/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampoSchema extends BaseModel {
  static $columns = ['categoriaId', 'createdAt', 'id', 'label', 'nome', 'obrigatorio', 'opcoes', 'ordem', 'tipo', 'updatedAt'] as const
  $columns = CampoSchema.$columns
  @column()
  declare categoriaId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare nome: string
  @column()
  declare obrigatorio: boolean | null
  @column()
  declare opcoes: string | null
  @column()
  declare ordem: number | null
  @column()
  declare tipo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategoriaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nome', 'slug', 'updatedAt'] as const
  $columns = CategoriaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string | null
  @column()
  declare slug: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RegistroSchema extends BaseModel {
  static $columns = ['ativo', 'categoriaId', 'codigoBarra', 'createdAt', 'createdBy', 'dadosJson', 'id', 'imagem', 'marca', 'modelo', 'nome', 'peso', 'preco', 'quantidade', 'sku', 'tags', 'unidade', 'updatedAt', 'updatedBy', 'validade'] as const
  $columns = RegistroSchema.$columns
  @column()
  declare ativo: boolean | null
  @column()
  declare categoriaId: number
  @column()
  declare codigoBarra: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column()
  declare dadosJson: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagem: string | null
  @column()
  declare marca: string | null
  @column()
  declare modelo: string | null
  @column()
  declare nome: string
  @column()
  declare peso: number | null
  @column()
  declare preco: number | null
  @column()
  declare quantidade: number | null
  @column()
  declare sku: string
  @column()
  declare tags: any | null
  @column()
  declare unidade: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: number | null
  @column.date()
  declare validade: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
