/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampoSchema extends BaseModel {
  static $columns = ['config', 'createdAt', 'id', 'label', 'nome', 'opcoes', 'tipo', 'updatedAt'] as const
  $columns = CampoSchema.$columns
  @column()
  declare config: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare nome: string
  @column()
  declare opcoes: any | null
  @column()
  declare tipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategoriaCampoSchema extends BaseModel {
  static $columns = ['campoId', 'categoriaId', 'configOverride', 'createdAt', 'id', 'labelOverride', 'obrigatorio', 'ordem', 'updatedAt'] as const
  $columns = CategoriaCampoSchema.$columns
  @column()
  declare campoId: number
  @column()
  declare categoriaId: number
  @column()
  declare configOverride: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare labelOverride: string | null
  @column()
  declare obrigatorio: boolean | null
  @column()
  declare ordem: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategoriaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nome', 'slug', 'updatedAt'] as const
  $columns = CategoriaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustosFixoSchema extends BaseModel {
  static $columns = ['ativo', 'categoria', 'createdAt', 'descricao', 'diaVencimento', 'id', 'nome', 'updatedAt', 'valor'] as const
  $columns = CustosFixoSchema.$columns
  @column()
  declare ativo: boolean
  @column()
  declare categoria: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descricao: string | null
  @column()
  declare diaVencimento: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare valor: number
}

export class RegistroSchema extends BaseModel {
  static $columns = ['ativo', 'categoriaId', 'codigoBarra', 'createdAt', 'createdBy', 'custo', 'dadosJson', 'id', 'imagem', 'marca', 'modelo', 'nome', 'peso', 'preco', 'quantidade', 'sku', 'tags', 'unidade', 'updatedAt', 'updatedBy', 'validade'] as const
  $columns = RegistroSchema.$columns
  @column()
  declare ativo: boolean | null
  @column()
  declare categoriaId: number
  @column()
  declare codigoBarra: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column()
  declare custo: number
  @column()
  declare dadosJson: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagem: string | null
  @column()
  declare marca: string | null
  @column()
  declare modelo: string | null
  @column()
  declare nome: string
  @column()
  declare peso: number | null
  @column()
  declare preco: number
  @column()
  declare quantidade: number | null
  @column()
  declare sku: string
  @column()
  declare tags: any | null
  @column()
  declare unidade: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: number | null
  @column.date()
  declare validade: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VendaItenSchema extends BaseModel {
  static $columns = ['createdAt', 'custoTotal', 'custoUnitario', 'id', 'lucroBruto', 'precoUnitario', 'produtoNome', 'produtoSku', 'quantidade', 'registroId', 'subtotal', 'updatedAt', 'vendaId'] as const
  $columns = VendaItenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare custoTotal: number
  @column()
  declare custoUnitario: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lucroBruto: number
  @column()
  declare precoUnitario: number
  @column()
  declare produtoNome: string
  @column()
  declare produtoSku: string | null
  @column()
  declare quantidade: number
  @column()
  declare registroId: number | null
  @column()
  declare subtotal: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vendaId: number
}

export class VendaSchema extends BaseModel {
  static $columns = ['createdAt', 'custoTotal', 'desconto', 'formaPagamento', 'id', 'lucroBruto', 'observacao', 'status', 'subtotal', 'total', 'updatedAt', 'usuarioId'] as const
  $columns = VendaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare custoTotal: number
  @column()
  declare desconto: number
  @column()
  declare formaPagamento: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lucroBruto: number
  @column()
  declare observacao: string | null
  @column()
  declare status: string
  @column()
  declare subtotal: number
  @column()
  declare total: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usuarioId: number | null
}
